# Generated by Django 2.0.4 on 2018-04-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0004_auto_20180410_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
