# Generated by Django 2.0.4 on 2018-04-10 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0005_userprofile_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
    ]
